version: "3.9"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/BUILD  # Mounts the local directory into the container
    working_dir: /BUILD
    command: ["sleep", "infinity"]  # Keeps the container running
    stdin_open: true
    tty: true
